import type { MarengoTariff } from '../src/marengoTariffTypes';

// User-supplied tariff. Store paise, retain source categories, and do not activate global pricing rules.
export const marengoTariff: MarengoTariff = {
  id: 'marengo-dectrocel-tariff-v1',
  name: 'New Dectrocel',
  scope: 'MARENGO',
  currency: 'INR',
  status: 'DRAFT',
  effectiveFrom: null,
  pendingConfirmations: [
    'Effective date pending confirmation. Historical charges are unchanged.',
    'MRI Brain Protocol: confirm whether INR 110 is additional to the brain study rate.',
    'Urgent/night surcharges and tax treatment are not specified.',
  ],
  rates: [
    { id: 'xr-first-view', modality: 'X RAY', bodyPart: 'Radiography', studies: 'Per view / First view', chargeType: 'BASE', unit: 'First view', amountMinor: 2500 },
    { id: 'xr-additional-view', modality: 'X RAY', bodyPart: 'Radiography', studies: 'Additional view', chargeType: 'ADDITIONAL_VIEW', unit: 'Additional view', amountMinor: 2000 },
    { id: 'xr-special-study', modality: 'X RAY', bodyPart: 'Special Study', studies: 'Scanogram, HSG, IVP, Barium, ASU, MCU, Fistulogram, Sinogram, Gastrografin, Cholangiogram, Ductography, Sialogram, RGU, IVU, Bone Age, OPG', chargeType: 'BASE', unit: 'Study', amountMinor: 15000 },
    { id: 'xr-mammography', modality: 'X RAY', bodyPart: 'Special Study', studies: 'Mammography (each side)', chargeType: 'BASE', unit: 'Side', amountMinor: 5500 },
    { id: 'ct-head', modality: 'CT', bodyPart: 'Head', studies: 'Brain, PNS, Maxillofacial, Orbits, Temporal Bone, Pituitary, Face, Sella, CBCT, ROC Fungal, Sinogram', chargeType: 'BASE', unit: 'Study', amountMinor: 22500 },
    { id: 'ct-brain-face', modality: 'CT', bodyPart: 'Brain & Face', studies: 'Brain & Face', chargeType: 'BASE', unit: 'Study', amountMinor: 28000 },
    { id: 'ct-small-body', modality: 'CT', bodyPart: 'Small Body', studies: 'KUB, Pelvis, Spine (individual studies - cervical/dorsal/lumbar/sacral/coccyx), Upper Abdomen, CV Junction', chargeType: 'BASE', unit: 'Study', amountMinor: 31500 },
    { id: 'ct-body', modality: 'CT', bodyPart: 'Body', studies: 'Abdomen & Pelvis, Enterography, Neck, Thorax, Urography, Cisternography', chargeType: 'BASE', unit: 'Study', amountMinor: 41000 },
    { id: 'ct-msk', modality: 'CT', bodyPart: 'MSK', studies: 'Each extremity (Shoulder, Arm, Elbow, Forearm, Wrist, Hand, Thumb, Hip Joints, Thigh, Knee, Leg, Ankle, Foot, Heel, SI Joint, TM Joints, PM Joint, Scapula, Clavicle, Foot With Ankle)', chargeType: 'BASE', unit: 'Study', amountMinor: 35500 },
    { id: 'ct-triphasic', modality: 'CT', bodyPart: 'Triphasic', studies: 'CT Abdomen & Pelvis Triphasic', chargeType: 'BASE', unit: 'Study', amountMinor: 38500 },
    { id: 'ct-angiography', modality: 'CT', bodyPart: 'Angiography', studies: 'Cerebral, Neck, Thoracic, Abdominal, Peripheral, Aortogram, Pulmonary, Renal, Venogram, Cardiac', chargeType: 'BASE', unit: 'Study', amountMinor: 60000 },
    { id: 'ct-whole-spine', modality: 'CT', bodyPart: 'Whole Spine', studies: 'Whole Spine', chargeType: 'BASE', unit: 'Study', amountMinor: 63700 },
    { id: 'ct-whole-body', modality: 'CT', bodyPart: 'Whole Body', studies: 'Whole Body', chargeType: 'BASE', unit: 'Study', amountMinor: 90000 },
    { id: 'ct-additional-charges', modality: 'CT', bodyPart: 'Additional Charges', studies: '3D, Perfusion, Contrast', chargeType: 'ADD_ON', unit: 'Additional item', amountMinor: 5500 },
    { id: 'mri-brain', modality: 'MRI', bodyPart: 'Brain', studies: 'Brain, Sella, PNS, Maxillofacial, Face, Orbits, IAC, Tongue, Temporal Bone, Upper Airway, ROC Fungal', chargeType: 'BASE', unit: 'Study', amountMinor: 39000 },
    { id: 'mri-small-body', modality: 'MRI', bodyPart: 'Small Body', studies: 'KUB, Pelvis, MRCP, Scrotum, Upper Abdomen, Spine (individual studies - cervical/dorsal/lumbar/sacral/coccyx)', chargeType: 'BASE', unit: 'Study', amountMinor: 38000 },
    { id: 'mri-body', modality: 'MRI', bodyPart: 'Body', studies: 'Abdomen & Pelvis, Thorax, Enterography, Neck, Urography, Perineum, Cisternography', chargeType: 'BASE', unit: 'Study', amountMinor: 48500 },
    { id: 'mri-msk', modality: 'MRI', bodyPart: 'MSK', studies: 'Each extremity (Shoulder, Arm, Elbow, Forearm, Wrist, Hand, Thumb, Hip Joints, Thigh, Knee, Leg, Ankle, Foot, Heel, SI Joint, TM Joints, PM Joint, Clavicle, Scapula)', chargeType: 'BASE', unit: 'Study', amountMinor: 52500, note: 'Foot with Ankle uses the dedicated INR 600 rate.' },
    { id: 'mri-foot-ankle', modality: 'MRI', bodyPart: 'Foot with Ankle', studies: 'Foot with Ankle', chargeType: 'BASE', unit: 'Study', amountMinor: 60000, note: 'Dedicated rate confirmed; takes precedence over MSK.' },
    { id: 'mri-angiography', modality: 'MRI', bodyPart: 'Angiography', studies: 'Pulmonary, Renal, Neck, Abdominal, Aortogram, Central Venogram, Peripheral Arms, Peripheral Legs', chargeType: 'BASE', unit: 'Study', amountMinor: 67500 },
    { id: 'mri-advanced', modality: 'MRI', bodyPart: 'Advanced Studies', studies: 'Axilla, Breast, Multiparametric studies, Fistulogram, Brachial Plexus, Defecogram, Neurography, Cranial Nerves, CSF Flow, Sleep Study', chargeType: 'BASE', unit: 'Study', amountMinor: 67500 },
    { id: 'mri-additional-studies', modality: 'MRI', bodyPart: 'Additional Studies', studies: 'MRA, MRV, Spectro, Cartigram, Arthrogram', chargeType: 'ADDITIONAL_STUDY', unit: 'Additional study', amountMinor: 22500 },
    { id: 'mri-brain-protocol', modality: 'MRI', bodyPart: 'Brain Protocol', studies: 'Epilepsy Protocol, Stroke Protocol', chargeType: 'PROTOCOL', unit: 'Protocol', amountMinor: 11000, note: 'Standalone versus additional protocol charge pending confirmation.' },
    { id: 'mri-cardiac', modality: 'MRI', bodyPart: 'Cardiac', studies: 'Cardiac', chargeType: 'BASE', unit: 'Study', amountMinor: 101000 },
    { id: 'mri-whole-spine', modality: 'MRI', bodyPart: 'Whole Spine', studies: 'Whole Spine', chargeType: 'BASE', unit: 'Study', amountMinor: 90000 },
    { id: 'mri-whole-body', modality: 'MRI', bodyPart: 'Whole Body', studies: 'Whole Body', chargeType: 'BASE', unit: 'Study', amountMinor: 150000 },
    { id: 'mri-screening', modality: 'MRI', bodyPart: 'Screening', studies: 'Screening', chargeType: 'BASE', unit: 'Study', amountMinor: 15000 },
    { id: 'mri-additional-charges', modality: 'MRI', bodyPart: 'Additional Charges', studies: 'Contrast', chargeType: 'ADD_ON', unit: 'Additional item', amountMinor: 6500 },
    { id: 'nmr-gamma-camera', modality: 'NMR', bodyPart: 'Gamma Camera', studies: 'Gamma Camera', chargeType: 'BASE', unit: 'Study', amountMinor: 50500 },
    { id: 'nmr-pet-ct', modality: 'NMR', bodyPart: 'PET CT', studies: 'PET CT', chargeType: 'BASE', unit: 'Study', amountMinor: 139000 },
  ],
};
